server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sst
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 17121283
mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl